### PR TITLE
Set version number in readme

### PR DESCRIPTION
**Pull request by domoritz**

### CODE REVIEW

**Comment by akheron** [comment]
Hey, and thanks for taking this project forward 😊

Not sure why we should be encouraging the users to use a specific version, rather than the latest one 🤔 `master` was obviously wrong because the default branch is `main`, though.

**Comment by domoritz** [comment]
Thanks for making the action in the first place!

I found that https://docs.github.com/en/actions/creating-actions/about-actions says people should use tagged versions. 

Screen Shot 2021-06-09 at 20 10 21

When you feel like we are ready, we could add a v1 and move the major version tag along with the latest version that does not break backwards compatibility.

Screen Shot 2021-06-09 at 20 11 23

**Comment by akheron** [comment]
That makes sense! I don’t think this action will see any breaking changes, so why not add a v1 tag right away?

**Comment by domoritz** [comment]
Sounds good to me.

**Comment by domoritz** [comment]
Done

**Pull request closed without merging**
